# Generated by Django 5.0.3 on 2024-04-03 16:53

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objects', api.models.ProfileManager()),
            ],
        ),
    ]
